# Site settings
title: 
header-img: img/home-bg.png
email: mjun@calstate.edu
copyright_name: marcusjun
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcusjun
learn_profile: marcusjun
email_username: mjun@calstate.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
